### ISSUE TITLE
Change the files order

### ISSUE THREAD

**Issue by abdonrd** [shellscape/prettier-plugin-package#12]
Right now the files are are ordered alphabetically.
Reference: https://github.com/shellscape/prettier-plugin-package#files
But the order of the imports are important.
I found this issue when I need to negate. When I write:

```json
  "files": [
    "src/**/*",
    "src-js/**/*",
    "!src-js/**/*.stories.d.ts",
    "!src-js/**/*.stories.js",
    "!src-js/**/*.stories.js.map",
    "custom-elements.json"
  ],
```

### Expected Behavior / Situation

```json
  "files": [
    "src/**/*",
    "src-js/**/*",
    "!src-js/**/*.stories.d.ts",
    "!src-js/**/*.stories.js",
    "!src-js/**/*.stories.js.map",
    "custom-elements.json"
  ],
```

### Actual Behavior / Situation

```json
  "files": [
    "!src-js/**/*.stories.d.ts",
    "!src-js/**/*.stories.js",
    "!src-js/**/*.stories.js.map",
    "custom-elements.json",
    "src-js/**/*",
    "src/**/*"
  ],
```

Here move the negations to the top, and this negations stop working.

### Modification Proposal

Maybe move all the negations to the bottom?

**Comment by shellscape** [comment]
You'd be much better off using `.npmignore` for that functionality, which is where I feel most people add negations.

**Comment by abdonrd** [comment]
In our projects we try to use the `package.json` fields instead of creating files. 😕 

In addition, in this project it is much easier for us to specify which files we want than to specify all the files we want to ignore.

**Comment by abdonrd** [comment]
Also I like the idea to respect the sort from the editor tree (VSCode for example), where the sort is like this:

```
src/
src-js/
custom-elements.json
```

Instead of this:

```
custom-elements.json
src-js/
src/
```

**Comment by shellscape** [comment]
One of the core tenets of Prettier is that it's opinionated and uniform. I can say with certainty that I'm not going to adopt any particular editor's sort order.

With regard to sorting for globs - there's no way I can predict what a user's preferred glob order is - and some tricky stuff can be done with them. Then there's the fact that some teams/users prefer smaller and more files, and some like yourself prefer larger and fewer files. That's not something I can cater to and still claim an opinionated package. Since npm supports the ignore file and globs work well there, that's the place to use them when leveraging this package.

Your best route here is probably to use a more flexible package, or fork this one and make the changes you'd like to see for your team. If you do fork, I'd recommend scoping your package name.

Thanks for opening and issue and for the suggestion, but I'm going to decline making that change for now.

**Comment by abdonrd** [comment]
Thanks for the answer @shellscape!

And what do you think about just remove the files order? To avoid break the npm behavior and keep using this plugin.

**Comment by shellscape** [comment]
For all of the teams and projects that I'm a part of, sorting the `files` property helps keep our package.json files clean and uniform, so I don't think that I would be open to removing sorting that property.

**Comment by abdonrd** [comment]
Ok, thanks @shellscape

**Comment by abdonrd** [comment]
Hi @shellscape! Could we at least move the negations (`!`) to the bottom of the list? This way I think it could work.

We also have this problem here: https://github.com/Polymer/lit-html/pull/1351

**Comment by shellscape** [comment]
@abdonrd yes I'd be open to that.

**Comment by abdonrd** [comment]
@shellscape thanks Andrew! Done at #17!
