### ISSUE TITLE
Making it Format Files Other than package.json

### ISSUE THREAD

**Issue by ProfessorManhattan** [shellscape/prettier-plugin-package#20]
Ok, so I tried getting this plugin to work for other formats like `package.hbs.json` and `package.json.handlebars` but I have had no luck. I have no idea why this plugin only formats package.json. I can't get anything other than a file named `package.json` to get into the parse function. Any ideas?

```
console.log(parser);
console.log(parse);
module.exports = {
  name: 'prettier-plugin-package-fix',
  extensions: [ // This seems to have no effect
    ".hbs",
    ".json",
    ".hbz.json",
   ".hbz"
  ],
  parsers: {
    'json-stringify': {
      ...parser,
      parse(...args) {
        const [, , options] = args;
        const { filepath } = options;
        const ast = parse(...args);
        console.log(filepath); // this only logs package.json and never anything else
        if (rePkg.test(filepath)) {
          const { properties } = ast;
          ast.properties = format(properties);
        }

        return ast;
      }
    }
  }
};
```

Totally confused. How does this plugin only run when its exactly named package.json?

**Comment by shellscape** [comment]
Well you really haven't given me anything to be able to help you. I suggest reading: https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

This line https://github.com/shellscape/prettier-plugin-package/blob/1d17aa1afe63c63942486999e88207831c363d86/lib/index.js#L21 and this line https://github.com/shellscape/prettier-plugin-package/blob/1d17aa1afe63c63942486999e88207831c363d86/lib/index.js#L43 would be safe bets as to why it's not working for the files you're targeting.

**Comment by ProfessorManhattan** [comment]
Hey @shellscape -- that doesn't help. For some reason, the parser only picks up package.json --- it doesn't even get to the check that we both pointed out. I dare you to figure it out --- you'll probably be scratching your head too :rofl:

**Comment by ProfessorManhattan** [comment]
@shellscape -- you can probably test it yourself just by trying to run prettier on anything that ends in `package.json`... according to the RegEx it should work but it wont

**Comment by shellscape** [comment]
It looks like you might be new, starting out. So a few pointers I'd like to share:

- I linked to an article on effective bug reporting. Your issue unfortunately, was not effective. This is important not only on Github, but any platform where you're providing feedback. This is a critical skill necessary for career advancement.
- I pointed to a few places in the source where it explicitly only works for `package.json` files. That means it's working as intended, and your use case, while likely frustrating and confusing, doesn't apply to the intent of the code in this repo. This project has no features which allow it to be used on alternate JSON files.
- Github has a very functional "edit" feature for issues, pull requests, and replies. Please use that rather than subsequent replies.
- It's not on a repo/project owner or maintainer to allow for your use case, especially given the above. That onus is on you as a consumer/user/tinkerer. Thus is open source.

Thanks for stopping by and for giving the project a try. I'm sorry that it didn't work out for you and that it's frustrating or confusing trying to apply it to your use case. Unfortunately there's not much I can do to help you and I unfortunately lack the time to help you triage what you're trying to accomplish. Best of luck.
